version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      non-major:
        update-types:
          - minor
          - patch
      discordjs:
        patterns:
          - "@discordjs/*"
        update-types:
          - major

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
